# ------------------------------------------------------
#
# This Dockerfile is NOT used with docker-compose.yml.
# This Dockerfile is used to create a single-container
# version of the application. To run this you only need Docker.
#
# ------------------------------------------------------

FROM bitnami/nginx
MAINTAINER Alex Karadimos

COPY dist /app