# ------------------------------------------------------
#
# This Dockerfile is NOT used with docker-compose.yml.
# This Dockerfile is used to create a single-container
# version of the application. To run this you only need Docker.
#
# ------------------------------------------------------

FROM phpmyadmin/phpmyadmin:latest
MAINTAINER Alex Karadimos

EXPOSE 80 443