# ------------------------------------------------------
#
# This Dockerfile is used along with docker-compose.yml
# to create a multi-container version of the application.
# To run this you need Docker as well as Docker-compose.
#
# ------------------------------------------------------

FROM haproxy:latest
MAINTAINER Alex Karadimos

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg