# ------------------------------------------------------
#
# This Dockerfile is used along with docker-compose.yml
# to create a multi-container version of the application.
# To run this you need Docker as well as Docker-compose.
#
# ------------------------------------------------------

FROM node:latest
MAINTAINER Alex Karadimos

EXPOSE 80 443